"""add noise_timeline to sleep_sessions

Revision ID: 03692896b39b
Revises: 2130d659665f
Create Date: 2026-07-13 23:20:47.902039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03692896b39b'
down_revision: Union[str, Sequence[str], None] = '2130d659665f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noise_timeline', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_column('noise_timeline')

    # ### end Alembic commands ###
