"""initial schema

Revision ID: 2130d659665f
Revises: 
Create Date: 2026-07-13 22:51:34.233442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2130d659665f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('refreshed', sa.Integer(), nullable=True),
    sa.Column('morning_energy', sa.Integer(), nullable=True),
    sa.Column('daytime_sleepiness', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('focus', sa.Integer(), nullable=True),
    sa.Column('stress', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('mental_clarity', sa.Integer(), nullable=True),
    sa.Column('physical_fatigue', sa.Integer(), nullable=True),
    sa.Column('afternoon_crash', sa.Integer(), nullable=True),
    sa.Column('workout_quality', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_date'), ['date'], unique=False)

    op.create_table('habit_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('caffeine_mg', sa.Float(), nullable=True),
    sa.Column('first_caffeine_time', sa.String(), nullable=True),
    sa.Column('last_caffeine_time', sa.String(), nullable=True),
    sa.Column('alcohol_units', sa.Float(), nullable=True),
    sa.Column('last_alcohol_time', sa.String(), nullable=True),
    sa.Column('nicotine', sa.Boolean(), nullable=True),
    sa.Column('cannabis', sa.Boolean(), nullable=True),
    sa.Column('medication', sa.String(), nullable=True),
    sa.Column('supplements', sa.String(), nullable=True),
    sa.Column('last_meal_time', sa.String(), nullable=True),
    sa.Column('meal_size', sa.String(), nullable=True),
    sa.Column('exercise_type', sa.String(), nullable=True),
    sa.Column('exercise_intensity', sa.String(), nullable=True),
    sa.Column('exercise_end_time', sa.String(), nullable=True),
    sa.Column('morning_light_start', sa.String(), nullable=True),
    sa.Column('morning_light_minutes', sa.Float(), nullable=True),
    sa.Column('evening_screens', sa.String(), nullable=True),
    sa.Column('wind_down_routine', sa.Boolean(), nullable=True),
    sa.Column('nap_start', sa.String(), nullable=True),
    sa.Column('nap_minutes', sa.Float(), nullable=True),
    sa.Column('hydration', sa.String(), nullable=True),
    sa.Column('illness', sa.Boolean(), nullable=True),
    sa.Column('pain', sa.Boolean(), nullable=True),
    sa.Column('travel', sa.Boolean(), nullable=True),
    sa.Column('timezone_change', sa.Boolean(), nullable=True),
    sa.Column('bedroom_temp', sa.String(), nullable=True),
    sa.Column('bedroom_noise', sa.String(), nullable=True),
    sa.Column('bedroom_light', sa.String(), nullable=True),
    sa.Column('sleeping_position', sa.String(), nullable=True),
    sa.Column('partner_in_room', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_observations_date'), ['date'], unique=True)

    op.create_table('import_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_sha256', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('staged_payload', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('work_schedule', sa.String(), nullable=True),
    sa.Column('required_wake_time', sa.String(), nullable=True),
    sa.Column('workdays', sa.JSON(), nullable=True),
    sa.Column('training_schedule', sa.Text(), nullable=True),
    sa.Column('travel_status', sa.String(), nullable=True),
    sa.Column('primary_goals', sa.JSON(), nullable=True),
    sa.Column('sleep_concerns', sa.JSON(), nullable=True),
    sa.Column('preferred_units', sa.String(), nullable=False),
    sa.Column('current_timezone', sa.String(), nullable=False),
    sa.Column('target_sleep_minutes', sa.Integer(), nullable=False),
    sa.Column('hide_nightly_scores', sa.Boolean(), nullable=False),
    sa.Column('preferred_sources', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('record_kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('raw_record_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_session_id', sa.String(), nullable=True),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('session_date', sa.String(), nullable=False),
    sa.Column('timezone_name', sa.String(), nullable=False),
    sa.Column('in_bed_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_onset_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_wake_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('out_of_bed_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_in_bed_min', sa.Float(), nullable=True),
    sa.Column('total_sleep_min', sa.Float(), nullable=True),
    sa.Column('sleep_latency_min', sa.Float(), nullable=True),
    sa.Column('waso_min', sa.Float(), nullable=True),
    sa.Column('awakenings_count', sa.Integer(), nullable=True),
    sa.Column('stage_intervals', sa.JSON(), nullable=True),
    sa.Column('is_nap', sa.Boolean(), nullable=False),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('snore_minutes', sa.Float(), nullable=True),
    sa.Column('noise_level', sa.Float(), nullable=True),
    sa.Column('cycles', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_fraction', sa.Float(), nullable=True),
    sa.Column('movement_timeline', sa.JSON(), nullable=True),
    sa.Column('event_timeline', sa.JSON(), nullable=True),
    sa.Column('field_provenance', sa.JSON(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_breakdown', sa.JSON(), nullable=True),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('excluded_reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_sessions_session_date'), ['session_date'], unique=False)

    op.create_table('physio_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('original_field', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sleep_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physio_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physio_observations_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_physio_observations_metric'), ['metric'], unique=False)

    op.create_table('snore_observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('recording_start_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('total_snore_min', sa.Float(), nullable=True),
    sa.Column('background_noise', sa.Float(), nullable=True),
    sa.Column('audio_confidence', sa.String(), nullable=False),
    sa.Column('non_snore_flag', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sleep_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snore_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snore_observations_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snore_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snore_observations_date'))

    op.drop_table('snore_observations')
    with op.batch_alter_table('physio_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physio_observations_metric'))
        batch_op.drop_index(batch_op.f('ix_physio_observations_date'))

    op.drop_table('physio_observations')
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_session_date'))

    op.drop_table('sleep_sessions')
    op.drop_table('raw_records')
    op.drop_table('user_profile')
    op.drop_table('import_batches')
    with op.batch_alter_table('habit_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_observations_date'))

    op.drop_table('habit_observations')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_date'))

    op.drop_table('checkins')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
